set number
set expandtab
set hlsearch
set ignorecase
set incsearch
set smartcase 
set laststatus=2
set nocompatible
syntax on
set autoindent
filetype plugin indent on
set showcmd
set background=dark
set wildmenu
set ruler
set showmatch
set cursorline
set hidden
set noerrorbells
set shellslash
